## SwiftLint configuration
## See https://github.com/realm/SwiftLint/blob/master/.swiftlint.yml
## Check rules at: https://github.com/realm/SwiftLint/blob/master/Rules.md

# rule identifiers to exclude from running
disabled_rules: 
  - blanket_disable_command
  - file_length
  - function_body_length
  - function_parameter_count
  - identifier_name
  - inclusive_language
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - todo
  - trailing_comma
  - type_name

opt_in_rules:
  - colon
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - empty_count
  - implicit_return
  - redundant_type_annotation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - toggle_bool

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - AlayaCare-iOS-CI/
  - App/BuildTools/
  - App/careworkerappSnapshotTests/
  - App/careworkerappTests/
  - App/careworkerappUITests/
  - mobile.common/
  - scripts/
  - Tests/

allow_zero_lintable_files: true

######## RULES ########

analyzer_rules: # rules run by `swiftlint analyze`
  - unused_import

colon: 
  severity: error
contains_over_filter_count: error
contains_over_filter_is_empty: error
contains_over_first_not_nil: error
contains_over_range_nil_comparison: error
cyclomatic_complexity:
  ignores_case_statements: true

empty_count:
  only_after_dot: true

force_cast: warning
force_try: warning

implicit_getter: error
identifier_name:
  excluded:
    - id
    - i
    - e

statement_position: 
  severity: error
trailing_semicolon: error
unneeded_parentheses_in_closure_argument: warning
